org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.9
minecraft_version_range=[1.21.9,1.21.11)
neo_version=21.9.16-beta
neo_version_range=[21.9.16-beta,21.11)

mod_id=ravengardplus
mod_name=Ravengard Plus
mod_license=Apache-2.0
mod_version=1.0.3
mod_group_id=com.seniors.ravengardplus

yacl_version=3.8.0+1.21.9-neoforge
yacl_version_range=[3.8.0,)
