plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = "${project.mod_version}+mc26.1-26.1.2"
group = project.maven_group

repositories {
	maven {
		name = 'Xander Maven'
		url = 'https://maven.isxander.dev/releases'
	}
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"ravengard-plus" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

sourceSets.client.java {
	setSrcDirs(['../src/client/java', 'src/client/java'])
	exclude 'com/seniors/ravengardplus/client/mixin/HudMixin.java'
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	implementation "dev.isxander:yet-another-config-lib:${project.yacl_version}"
}

processResources {
	def version = project.version
	inputs.property 'version', version

	filesMatching('fabric.mod.json') {
		expand 'version': version
	}

	from('../src/client/resources/assets') {
		into 'assets'
	}
	from('../src/main/resources/assets') {
		into 'assets'
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	def projectName = project.name
	inputs.property 'projectName', projectName

	from('../LICENSE') {
		rename { "${it}_${projectName}" }
	}
}

publishing {
	publications {
		create('mavenJava', MavenPublication) {
			from components.java
		}
	}
}
