org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.5
minecraft_version_range=[1.21.5]
neo_version=21.5.98
neo_version_range=[21.5.98,21.6)

mod_id=ravengardplus
mod_name=Ravengard Plus
mod_license=Apache-2.0
mod_version=1.0.3
mod_group_id=com.seniors.ravengardplus

yacl_version=3.8.1+1.21.5-neoforge
yacl_version_range=[3.8.1,)
